
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'app-instance-cadvisor'
    static_configs:
      - targets: ['<APP-INSTANCE-PUBLIC-IP>:8080']

  - job_name: 'app-instance-node'
    static_configs:
      - targets: ['<APP-INSTANCE-PUBLIC-IP>:9100']
